apps/blog/urls.py
from django.urls import path

from apps.blog.views import ArticleListView, ArticleDetailView, ContactView

app_name = "blog"
urlpatterns = [
    path("", ArticleListView.as_view(), name="articles"),
    path("articles/<pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("contact/", ContactView.as_view(), name="contact"),
]

apps/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.flatpages import views

urlpatterns = [
    path("", include("apps.blog.urls")),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
]

urlpatterns += [
    re_path(r"^(?P<url>.*/)$", views.flatpage),
]

blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

apps/blog/models.py
from django.db import models

class Article(models.Model):
    author = models.CharField(max_length=99)
    title = models.CharField(max_length=99)
    subtitle = models.CharField(max_length=99)
    content = models.TextField()
    published_date = models.DateField()
    is_published = models.BooleanField(default=False, blank=False)

    def __str__(self):
        return f"{self.title}: {self.subtitle} by {self.author}"

apps/blog/forms.py
import logging
import os

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from django import forms
from django.conf import settings
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

logger = logging.getLogger("django")


def sendgrid_mail(from_email, to_emails, reply_to, subject, html_content):
    message = Mail(
        from_email=from_email,
        to_emails=to_emails,
        subject=subject,
        html_content=html_content
    )
    message.reply_to = reply_to
    try:
        logging.info(settings.SENDGRID_API_KEY)
        sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
        response = sg.send(message)
    except Exception:
        logging.info("Sendgrid response status: %s", response.status_code)
        logging.info("SendGrid response body: %s", response.body)
        logging.info("SendGrid response headers: %s", response.headers)
        logging.exception("email was NOT sent")


class ContactForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["captcha"].label = False

    sender = forms.CharField(max_length=256)
    email = forms.EmailField(max_length=256)
    subject = forms.CharField(max_length=256)
    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(attrs=dict(cols=19, rows=10, placeholder="2000 character limit")),
    )
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

    helper = FormHelper()
    helper.add_input(Submit("submit", "Send Email"))
    helper.layout = Layout(
        Field("sender"),
        Field("email"),
        Field("subject"),
        Field("message"),
        Field('captcha', style="border: none; padding: 0px"),
    )

    def mail(self):
        logging.info("sending email via SendGrid")
        logging.info("form data %s", self.cleaned_data)
        sendgrid_mail(
            from_email=settings.FROM_EMAIL,
            to_emails=settings.TO_EMAIL,
            reply_to=self.cleaned_data["email"],
            subject=self.cleaned_data["subject"],
            html_content=self.cleaned_data["message"],
        )

apps/blog/views.py
from django.views.generic import DetailView, ListView
from django.contrib import messages
from django.views.generic.edit import FormView

from apps.blog.models import Article
from apps.blog.forms import ContactForm

import logging
logger = logging.getLogger("django")

class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog/post.html"


class ArticleListView(ListView):
    model = Article
    template_name = "blog/index.html"
    paginate_by = 2
    ordering = "-published_date"
    queryset = Article.objects.filter(is_published=True)



class ContactView(FormView):
    template_name = "blog/contact.html"
    form_class = ContactForm
    success_url = "/contact/"

    def form_valid(self, form:ContactForm):
        try:
            logging.info("the form is valid, call form.mail()")
            form.mail()
            logging.info("successfully called form.mail()")
            messages.success(self.request, "Your message was sent successfully")
        except Exception:
            messages.error(self.request, "Unable to send your message")
        return super().form_valid(form)

apps/blog/templates/blog/contact.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load static %}

{% block page_title %} Get in Touch {% endblock %}
{% block page_subtitle %} I'd Love to Hear from You {% endblock %}
{% block page_image %}{% static 'assets/img/contact-bg.jpg' %}{% endblock %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                <div class="my-5">
                {% crispy form %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

apps/blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block page_title %} Welcome to Elmquist.Dev {% endblock %}
{% block page_subtitle %} A Python Focused Look at Backend Software Engineering{% endblock %}
{% block page_image %}{% static 'assets/img/home-bg.jpg' %}{% endblock %}

{% block content %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">

            {% for article in article_list %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:article_detail' article.pk %}">
                    <h2 class="post-title">{{ article.title }}</h2>
                    <h3 class="post-subtitle">{{ article.subtitle }}</h3>
                </a>
                <p class="post-meta">
                    Posted by {{ article.author }}
                    on {{ article.published_date }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}

            <!-- Pager-->
            {% if is_paginated %}
            <div class="d-flex flex-row justify-content-between">

                <div class="d-flex justify-content-start mb-4">
                    <a
                        class="btn btn-primary text-uppercase{% if not page_obj.has_previous %} disabled{% endif %}"
                        {% if page_obj.has_previous %}
                        href="/?page={{ page_obj.previous_page_number }}"
                        {% endif %}
                    >
                        <<
                    </a>
                </div>

                <div class="d-flex justify-content-center mb-4">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </div>

                <div class="d-flex justify-content-end mb-4">
                    <a
                        class="btn btn-primary text-uppercase{% if not page_obj.has_next %} disabled{% endif %}"
                        {% if page_obj.has_next %}
                        href="/?page={{ page_obj.next_page_number }}"
                        {% endif %}
                    >
                        >>
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/post.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'assets/img/post-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{ article.title }}</h1>
                    <h2 class="subheading">{{ article.subtitle }}</h2>
                    <span class="meta">
                        Posted by {{ article.author }} on {{ article.published_date }}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {{ article.content | safe }}
            </div>
        </div>
    </div>
</article>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/googlecode.min.css">
{% endblock %}

{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/python.min.js"></script>
    <script>hljs.highlightAll();</script>
{% endblock %}

apps/templates/base.html
{% load static %}
{% load flatpages %}
{% get_flatpages as flatpages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>elmquist.dev</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
          rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">elmquist.dev</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">

            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/about/">About</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/contact/">Contact</a></li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" id="navbarDropdownBlog" href="#"
                       role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Extras
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                        {% for page in flatpages %}
                        <li><a class="dropdown-item" href="{{ page.url }}">{{ page.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% block page_image %}{% endblock %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{% block page_title %}{% endblock %}</h1>
                    <span class="subheading">{% block page_subtitle %}{% endblock %}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}{% endblock %}

<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://www.linkedin.com/in/aaron-e-99800839/">
                            <span class="fa-stack fa-lg">
                                <i class="fab fa-linkedin fa-stack-2x"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/elmq0022">
                            <span class="fa-stack fa-lg">
                                <i class="fa-brands fa-github fa-stack-2x"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; elmquist.dev 2024</div>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
{% block extra_css %}{% endblock %}
{% block extra_js %}{% endblock %}
</html>